# Schema for the configuration files of the OpenChurch Theme theme.
openchurch_theme.settings:
  type: theme_settings
  label: 'OpenChurch Theme settings'
  mapping:
    button_color:
      type: textfield
      label: Button Color
    button_border:
      type: textfield
      label: Button Border
    button_hover:
      type: textfield
      label: Button Hover
    button_hover_border:
      type: textfield
      label: Button Hover Border
